# age = input("Enter your age: ")
# print(age)
# age = int(age)
# print(type(age))
# name = input("Enter your name: ")
# print(name)
# print(type(name))
# height = input("Enter your height: ")
# print(height)
# height = float(height)
# print(type(height))
# weight = input("Enter your weight: ")
# print(weight)
# weight = float(weight)
# print(type(weight))
qualification = input("Enter your qualification: ")
print(qualification)
print(type(qualification))
employer = input("Enter your employer details: ")
print(employer)
print(type(employer))
license_holder = input("Enter you are eligible: ")
print(license_holder)
license_holder = bool(license_holder)
print(type(license_holder))

